server:
  port: 8080
  servlet:
    context-path: /demo-stream-kafka
logging:
  level:
    root: ERROR
    com.example.demoStreamKafka.consumer: INFO
spring:
  docker:
    compose:
      skip:
        in-tests: false
      file: "file:@project.basedir@/src/main/resources/compose/docker-compose.yml"
      lifecycle-management: start-and-stop
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    function:
      definition: productConsumer;productConsumer2;productMessageConsumer:productMessageConsumer2;productBatchListConsumer;productBatchListConsumer2;productBatchListMessageConsumer;productBatchListMessageConsumer2
    stream:
      output-bindings: foo-out-0
      bindings:
        # single record consumers
        productConsumer-in-0:
          group: my-group-productConsumer
          destination: input-topic
        productConsumer2-in-0:
          group: my-group-productConsumer2
          destination: input-topic
        productMessageConsumer-in-0:
          group: my-group-productMessageConsumer
          destination: input-topic
        productMessageConsumer2-in-0:
          group: my-group-productMessageConsumer2
          destination: input-topic
        productBatchListConsumer-in-0:
          group: my-group-productBatchListConsumer
          destination: input-topic
        # batch consumers
        productBatchListConsumer2-in-0:
          group: my-group-productBatchListConsumer2
          destination: input-topic
          consumer:
            batch-mode: true
        productBatchListMessageConsumer-in-0:
          group: my-group-productBatchListMessageConsumer
          destination: input-topic
          consumer:
            batch-mode: true
        productBatchListMessageConsumer2-in-0:
          group: my-group-productBatchListMessageConsumer2
          destination: input-topic
          consumer:
            batch-mode: true
        # output binding
        foo-out-0:
          destination: input-topic
          content-type: application/json

management:
  health:
    binders:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS

